# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
bzip2=1.0.8=h99b78c6_7
ca-certificates=2024.7.4=hf0a4a13_0
click=8.1.7=unix_pyh707e725_0
libblas=3.9.0=23_osxarm64_openblas
libcblas=3.9.0=23_osxarm64_openblas
libcxx=18.1.8=h167917d_2
libexpat=2.6.2=hebf3989_0
libffi=3.4.2=h3422bc3_5
libgfortran=5.0.0=13_2_0_hd922786_3
libgfortran5=13.2.0=hf226fd6_3
liblapack=3.9.0=23_osxarm64_openblas
libopenblas=0.3.27=openmp_h517c56d_1
libsqlite=3.46.0=hfb93653_0
libzlib=1.3.1=hfb2fe0b_1
llvm-openmp=18.1.8=hde57baf_0
ncurses=6.5=hb89a1cb_0
numpy=2.0.1=py312hb544834_0
openssl=3.3.1=hfb2fe0b_2
pandas=2.2.2=py312h8ae5369_1
pip=24.2=pyhd8ed1ab_0
python=3.12.4=h30c5eda_0_cpython
python-dateutil=2.9.0=pyhd8ed1ab_0
python-tzdata=2024.1=pyhd8ed1ab_0
python_abi=3.12=4_cp312
pytz=2024.1=pyhd8ed1ab_0
readline=8.2=h92ec313_1
setuptools=71.0.4=pyhd8ed1ab_0
six=1.16.0=pyh6c4a22f_0
tk=8.6.13=h5083fa2_1
tzdata=2024a=h0c530f3_0
wheel=0.43.0=pyhd8ed1ab_1
xz=5.2.6=h57fd34a_0
